import type { Language } from '@/types/browser';

export const LANGUAGES: Record<Language, { name: string; native: string; dir: 'ltr' | 'rtl'; font: string }> = {
  en: { name: 'English', native: 'English', dir: 'ltr', font: 'Inter' },
  ur: { name: 'Urdu', native: 'اردو', dir: 'rtl', font: 'Noto Nastaliq Urdu' },
  ar: { name: 'Arabic', native: 'العربية', dir: 'rtl', font: 'Amiri' },
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    browserName: 'ES Browser',
    newTab: 'New Tab',
    search: 'Search or enter URL',
    bookmarks: 'Bookmarks',
    history: 'History',
    downloads: 'Downloads',
    settings: 'Settings',
    admin: 'Admin Panel',
    gallery: 'Gallery',
    mediaPlayer: 'Media Player',
    home: 'Home',
    reload: 'Reload',
    back: 'Back',
    forward: 'Forward',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    loading: 'Loading...',
    noResults: 'No results found',
    welcomeTitle: 'Welcome to ES Browser',
    welcomeSubtitle: 'Fast. Secure. Beautiful.',
  },
  ur: {
    browserName: 'ای ایس براؤزر',
    newTab: 'نیا ٹیب',
    search: 'تلاش کریں یا URL درج کریں',
    bookmarks: 'بک مارکس',
    history: 'تاریخ',
    downloads: 'ڈاؤنلوڈز',
    settings: 'ترتیبات',
    admin: 'ایڈمن پینل',
    gallery: 'گیلری',
    mediaPlayer: 'میڈیا پلیئر',
    home: 'ہوم',
    reload: 'ریلوڈ',
    back: 'پیچھے',
    forward: 'آگے',
    close: 'بند کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    delete: 'حذف',
    edit: 'ترمیم',
    add: 'شامل کریں',
    loading: 'لوڈ ہو رہا ہے...',
    noResults: 'کوئی نتیجہ نہیں ملا',
    welcomeTitle: 'ای ایس براؤزر میں خوش آمدید',
    welcomeSubtitle: 'تیز۔ محفوظ۔ خوبصورت۔',
  },
  ar: {
    browserName: 'متصفح ES',
    newTab: 'علامة تبويب جديدة',
    search: 'ابحث أو أدخل عنوان URL',
    bookmarks: 'الإشارات المرجعية',
    history: 'التاريخ',
    downloads: 'التنزيلات',
    settings: 'الإعدادات',
    admin: 'لوحة الإدارة',
    gallery: 'المعرض',
    mediaPlayer: 'مشغل الوسائط',
    home: 'الرئيسية',
    reload: 'تحديث',
    back: 'رجوع',
    forward: 'تقدم',
    close: 'إغلاق',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    loading: '...جار التحميل',
    noResults: 'لا توجد نتائج',
    welcomeTitle: 'مرحباً بك في متصفح ES',
    welcomeSubtitle: 'سريع. آمن. جميل.',
  },
};

export const SEARCH_ENGINES = [
  { id: 'google', name: 'Google', url: 'https://www.google.com/search?q=', icon: 'G' },
  { id: 'bing', name: 'Bing', url: 'https://www.bing.com/search?q=', icon: 'B' },
  { id: 'duckduckgo', name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=', icon: 'D' },
  { id: 'yahoo', name: 'Yahoo', url: 'https://search.yahoo.com/search?p=', icon: 'Y' },
  { id: 'brave', name: 'Brave', url: 'https://search.brave.com/search?q=', icon: 'Br' },
];
