import type { Launcher } from '@/types/browser';

export const LAUNCHERS: Launcher[] = [
  {
    id: 'crystal',
    name: 'Crystal White',
    description: 'Pure milky white with emerald accents',
    primary: '#10b981',
    secondary: '#dc2626',
    accent: '#f59e0b',
    bg: 'from-white via-emerald-50 to-white',
    preview: ['bg-white', 'bg-emerald-100', 'bg-red-100'],
  },
  {
    id: 'emerald',
    name: 'Emerald Glow',
    description: 'Deep emerald with crystalline white surfaces',
    primary: '#059669',
    secondary: '#0d9488',
    accent: '#10b981',
    bg: 'from-emerald-50 via-teal-50 to-white',
    preview: ['bg-emerald-100', 'bg-teal-100', 'bg-white'],
  },
  {
    id: 'crimson',
    name: 'Crimson Fire',
    description: 'Bold crimson with white luminous base',
    primary: '#dc2626',
    secondary: '#e11d48',
    accent: '#f97316',
    bg: 'from-red-50 via-rose-50 to-white',
    preview: ['bg-red-100', 'bg-rose-100', 'bg-white'],
  },
  {
    id: 'midnight',
    name: 'Midnight Frost',
    description: 'Deep navy frost on bright white canvas',
    primary: '#1e40af',
    secondary: '#7c3aed',
    accent: '#06b6d4',
    bg: 'from-blue-50 via-indigo-50 to-white',
    preview: ['bg-blue-100', 'bg-indigo-100', 'bg-white'],
  },
  {
    id: 'aurora',
    name: 'Aurora Borealis',
    description: 'Northern lights palette on white',
    primary: '#0891b2',
    secondary: '#7c3aed',
    accent: '#10b981',
    bg: 'from-cyan-50 via-purple-50 to-emerald-50',
    preview: ['bg-cyan-100', 'bg-purple-100', 'bg-emerald-100'],
  },
  {
    id: 'diamond',
    name: 'Diamond Luxury',
    description: 'Golden diamond with pure white luxury',
    primary: '#d97706',
    secondary: '#b45309',
    accent: '#10b981',
    bg: 'from-amber-50 via-yellow-50 to-white',
    preview: ['bg-amber-100', 'bg-yellow-100', 'bg-white'],
  },
  {
    id: 'neon',
    name: 'Neon Digital',
    description: 'Electric neon on bright white digital display',
    primary: '#8b5cf6',
    secondary: '#ec4899',
    accent: '#10b981',
    bg: 'from-violet-50 via-pink-50 to-white',
    preview: ['bg-violet-100', 'bg-pink-100', 'bg-white'],
  },
  {
    id: 'arctic',
    name: 'Arctic Ice',
    description: 'Ultra-cool arctic blue on icy white',
    primary: '#0284c7',
    secondary: '#0891b2',
    accent: '#10b981',
    bg: 'from-sky-50 via-cyan-50 to-white',
    preview: ['bg-sky-100', 'bg-cyan-100', 'bg-white'],
  },
];
